---
# Handlers for setup_server role

- name: restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted
  become: true

- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
  become: true
