---
# Handlers for setup_server role

- name: restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted
  become: true

- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
  become: true

- name: restore_rules
  community.general.iptables_state:
    state: restored
    table: filter
    path: /etc/iptables/ansible_filter.rules
    noflush: true          # ne touche pas aux chaînes Docker
  become: true

- name: save_fw
  community.general.iptables_state:
    state: saved
    table: filter
    path: /etc/iptables/rules.v4
  become: true