# .sops.yaml (repo root)

# Define once (anchor)
recipients: &recipients
  - age1xpcejmetxh5une6hp9dkpvqte0py8ujkym8ks3k3w5fuy802ae6q2c8sj9
creation_rules:
  # YAML / JSON (encrypt all values)
  - path_regex: '(.+)\.(ya?ml|json)(\.sec)?$'
    encrypted_regex: '^(.*)$'
    key_groups:
      - age: *recipients
    mac: 'ENC'

  # Terraform vars (prefer .tfvars.json)
  - path_regex: '(.+)\.tfvars\.json$'
    encrypted_regex: '^(.*)$'
    key_groups:
      - age: *recipients
    mac: 'ENC'

  # dotenv / INI
  - path_regex: '(.+)\.(env|ini)$'
    encrypted_regex: '^(.*)$'
    key_groups:
      - age: *recipients
    mac: 'ENC'
  
  # Fichiers de clés dédiées au state Tofu : on chiffre le(s) champ(s) clé(s)
  - path_regex: '^keys/tofu-.*\.sops\.yaml$'
    encrypted_regex: '^(tofu_state_key_base64)$'
    key_groups:
      - age: *recipients
    mac: 'ENC'
