---
# Default variables for setup_server role
# These can be overridden in group_vars, host_vars, or vault files

# SSH Configuration
ssh_port: 22

# Admin user configuration
# admin_username: "admin"  # Should be defined in inventory or group_vars
# admin_ssh_public_keys:   # Should be defined in vault or group_vars
#   - "ssh-rsa AAAA..."

# Ansible user SSH keys
# ansible_ssh_public_keys: # Should be defined in vault or group_vars
#   - "ssh-rsa AAAA..."

# Server configuration
timezone: "Europe/Paris"

# Package list (can be extended)
essential_packages:
  - iptables
  - curl
  - wget
  - git
  - htop
  - iptables-persistent
  - fail2ban
  - unzip
  - vim
  - ca-certificates
  - gnupg

# Fail2Ban SSH jail settings
fail2ban_ssh_maxretry: 3
fail2ban_ssh_bantime: 7200
fail2ban_ssh_findtime: 1200


firewall_input_safety_rules:
  - { in_interface: lo, jump: ACCEPT, comment: "safety-lo" }
  - { ctstate: "ESTABLISHED,RELATED", jump: ACCEPT, comment: "safety-established" }